development:
  access_key_id: AKIAIIO42QHVUX2KWYYA
  secret_access_key: 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

production:
  access_key_id: AKIAIIO42QHVUX2KWYYA
  secret_access_key: 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